#!/usr/bin/env bash
#read -p "Instructions here " var #variable name
if cat /etc/*-release | grep 'Arch Linux' #check if system is arch linux 
  then sudo pacman -Syyu #if yes update it else assuming its debian based ( not thinking of fedoras)
  else sudo apt-get update # should add conditions for debian type too
fi
